#pragma once
#include "Mesh.h"
#include <Model.h>

enum EngineParts {
	valve_cover,
	head,
	oil_pan,
	block,
	rod_piston_4_003,
	rod_piston_4_002,
	rod_piston_4_001,
	crank_gears,
	crank_pulley,
	cyl4_exh_vlv1,
	cyl4_exh_vlv2,
	cyl4_int_vlv1,
	cyl4_int_vlv2,
	cyl1_int_vlv2,
	cyl1_int_vlv1,
	cyl1_exh_vlv2,
	cyl1_vlv_exh1,
	cyl2_exh_vlv1,
	cyl3_exh_vlv1,
	cyl3_exh_vlv2,
	cyl2_exh_vlv2,
	cyl3_int_vlv2,
	cyl2_int_vlv1,
	cyl3_int_vlv1,
	piston_2,
	piston_3,
	piston_1,
	cyl2_int_vlv2,
	crank_1_bearing,
	crank_1,
	crank_2_bearing,
	crank_2,
	crank_3,
	crank_3_bearing,
	crank_4_bearing,
	piston_4,
	rod_piston_4,
	crank_4,
	exhaust,
	intake,
	air_filter,
	Font,
	cam_int,
	cam_gears_exh,
	cam_pulley_exh,
	cam_cyl3_int2,
	cam_cyl2_int1,
	cam_cyl1_int2,
	cam_cyl1_int1,
	cam_cyl3_int1,
	cam_cyl4_int1,
	cam_cyl2_int2,
	cam_cyl4_int2,
	cam_exh,
	cam_gears_int,
	cam_pulley_int,
	cam_cyl4_exh2,
	cam_cyl3_exh2,
	cam_cyl_2_exh2,
	cam_cyl4_exh1,
	cam_cyl3_exh1,
	cam_cyl2_exh1,
	cam_cyl1_exh1,
	cam_cyl1_exh2,
};

const std::string partsNames[] = {
	"valve_cover",
	"head",
	"oil_pan",
	"block",
	"rod_piston_4.003",
	"rod_piston_4.002",
	"rod_piston_4.001",
	"crank_gears",
	"crank_pulley",
	"cyl4_exh_vlv1",
	"cyl4_exh_vlv2",
	"cyl4_int_vlv1",
	"cyl4_int_vlv2",
	"cyl1_int_vlv2",
	"cyl1_int_vlv1",
	"cyl1_exh_vlv2",
	"cyl1_vlv_exh1",
	"cyl2_exh_vlv1",
	"cyl3_exh_vlv1",
	"cyl3_exh_vlv2",
	"cyl2_exh_vlv2",
	"cyl3_int_vlv2",
	"cyl2_int_vlv1",
	"cyl3_int_vlv1",
	"piston_2",
	"piston_3",
	"piston_1",
	"cyl2_int_vlv2",
	"crank_1_bearing",
	"crank_1",
	"crank_2_bearing",
	"crank_2",
	"crank_3",
	"crank_3_bearing",
	"crank_4_bearing",
	"piston_4",
	"rod_piston_4",
	"crank_4",
	"exhaust",
	"intake",
	"air_filter",
	"Font",
	"cam_int",
	"cam_gears_exh",
	"cam_pulley_exh",
	"cam_cyl3_int2",
	"cam_cyl2_int1",
	"cam_cyl1_int2",
	"cam_cyl1_int1",
	"cam_cyl3_int1",
	"cam_cyl4_int1",
	"cam_cyl2_int2",
	"cam_cyl4_int2",
	"cam_exh",
	"cam_gears_int",
	"cam_pulley_int",
	"cam_cyl4_exh2",
	"cam_cyl3_exh2",
	"cam_cyl_2_exh2",
	"cam_cyl4_exh1",
	"cam_cyl3_exh1",
	"cam_cyl2_exh1",
	"cam_cyl1_exh1",
	"cam_cyl1_exh2",
};

class EngineObject
{
public:
	EngineObject();
	Mesh* getMesh(EngineParts part);


	void drawPiston(float rotation);
	void drawValves(float rotation);

private:
	Model model;
};

